### ISSUE TITLE
Music Variety + Changes Too Often during Biome Change

### ISSUE THREAD

**Issue by pdoktor** [CircuitLord/ReactiveMusic#2]
I really, really love this mod, but honestly, the music variety is kinda lacking and I keep hearing the same 8+ songs over and over because it's the only songs that play in that specific biome. Also, it changing every time you switch biomes can get really, really annoying if you have terrain generation mods like Tectonic.

**Comment by CircuitLord** [comment]
Hey thanks for the feedback! I definitely agree with that, it's my main issue with a lot of music mods that they have the same music over and over and I'd like to make the experience with it as good as possible, more like vanilla minecraft where it's rarer/not repeating

I'll be taking a crack at improving this at some point!

**Comment by CircuitLord** [comment]
This is now fixed as of latest, I've added a new system that will be part of the user songpack configuration that lets you define if a song should always play when it's event happens, which is default false, meaning the music won't change as often.
